name: mydota
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.3.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    dio: ^5.4.3+1
    provider: ^6.1.2
    shimmer: ^3.0.0
    sqflite: ^2.3.3+1
    path: ^1.9.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0
    flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/dpc.png"

flutter:
    uses-material-design: true
    assets:
        - assets/
    fonts:
        - family: Poppins
          fonts:
              - asset: fonts/Poppins-Regular.ttf
